name    'jhoblitt-selenium'
version '0.2.3'

author 'Joshua Hoblitt <jhoblitt@cpan.org>'
license 'Apache'
project_page 'https://github.com/jhoblitt/puppet-selenium'
source 'https://github.com/jhoblitt/puppet-selenium.git'
summary 'Manages Selenium Server 2 - Standalone and Grid'
description 'Manages Selenium Server 2 - Standalone and Grid'
dependency 'puppetlabs/stdlib', '>= 3.0.0'
dependency 'maestrodev/wget', '>= 1.2.2'
dependency 'rodjek/logrotate', '>= 1.1.1'
